name: 6000.0.37f1-Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  editor-tests:
    uses: ./.github/workflows/main.yml
    with:
      projectPath: './'
      unityVersion: '6000.0.37f1'
      testMode: 'standalone'
    secrets: inherit